-- This migration never actually applied to any real environment. It
-- attempts to CREATE TABLE public.automations and CREATE TYPE
-- public.automation_status, both of which the earlier migration
-- 20260127204449_88e41d48-e992-4548-9fe0-3cf18d04e0c4.sql already created
-- (with a different, incompatible schema and a different set of enum
-- values) - a fresh replay of these migrations in order fails right here.
--
-- Confirmed directly against live production (2026-08-29): the actual
-- `automations` table's columns (id, user_id, name, description, trigger,
-- schedule, platforms, status, actions, conditions, last_run, next_run,
-- run_count, created_at, updated_at) match the *first* migration exactly,
-- not this one - this file's version is not what's running. It's also
-- absent from Supabase's own applied-migrations ledger
-- (`supabase_migrations.schema_migrations`), confirming it never
-- successfully ran anywhere, so rewriting it here isn't rewriting history
-- that actually happened.
--
-- Left in place (rather than deleted) as a historical record, neutralized
-- so a fresh migration replay - e.g. rebuilding a disposable test project
-- from these files - no longer fails on it. See docs/MASTER_CHECKLIST.md,
-- Phase 9 and Phase 11, for how this was found and why live introspection
-- (not a migration replay) was used to build the E2E test project's schema
-- in the meantime.
SELECT 1;
